remote_theme: chriskyfung/amp-affiliately-jekyll-theme

name: "Chris KY FUNG's Page"
title: "An Open Source Project Page"
description: "An open source project about ................"
url: https://chriskyfung.github.io
baseurl: '/my-mini-project'
repository: chriskyfung/my-mini-project
favicon: 'assets/images/favicon_96x96.png'
logo: 'assets/images/logo-plainSVG.svg'
timezone: 'Asia/Hong_Kong'

# Set <USERNAME>/<PROJECT> to display the button to the project
repository: chriskyfung/amp-affiliately-jekyll-theme

# Navigation features
nav:
  buttons:
    gh_sponsors: true # Show GitHub Sponsors button
  global:
    menu: false
    dropdown: false # Show menu with dropdown submenu
  local:
    items:
      - name: Features
        url: category/feature/
      - name: Docs
        url: category/doc/
      - name: Samples
        url: category/sample/
    menu: true
    title:
      limit: 40

# List Sorting
sort_categories: false
sort_tags: false

# Content Post-processing
target_blank: false
anchor_link: true

sidebar:
  featured: false
  recent_posts: false

# Disqus Comments
amp_disqus: 
  shortname: 'chriskyfung' # Disqus shortname
  url: 'https://chriskyfung.gitlab.io/disqus-amp/' #baseurl of your AMP disqus iframe element
  height: 580

# Google Custom Search Engine ID
cse_id: 011006674894885990812:tjln7k0nyjx 

# Analytics
ga4: 'G-HP4LN87NJE' # Google Analytics 4 Measurement ID

# Google Ads
adsense: 
  client_id: 'ca-pub-4819282024314540' # Google Adsense client ID
  ad_slot:
    before_content: 2454411055 # Ad Slot that places before content
    sidebar: 1391498756 # Ad Slot that places to sidebar

# Soical Buttons
social:
  facebook: chriskyfung
  pinterest: chriskyfung
  github : chriskyfung
  medium: chriskyfung

# Buy Me a Coffee
buymeacoffee: chriskyfung

# Copyright Start Year
copyright: 
  owner: Chris KY FUNG
  link: https://chriskyfung.github.io/

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

authors:
  chris:
    name: Chris KY Fung
    display_name: Chris F.
    gravatar: abd876486b2caa54b43bf64a5a86f620
    email: 
    web: https://en.gravatar.com/chrisfungky
    facebook: https://www.facebook.com/chriskyfung/
    description: "Author of this blog, M.Phil."

plugins:
  - github-pages
  - jekyll-seo-tag
