name: CI

on:
  pull_request:

# Ensures that only one workflow run is triggered for the latest commit on a pull request.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true
          cache-version: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install node dependencies
        run: pnpm install --frozen-lockfile
      - name: Build site
        run: |
          npm run css:build
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          NODE_ENV: production
      - name: Optimize AMP ⚡ and Minify HTML 🗜
        run: |
          sudo chmod -R 777 ./_site
          npx gulp build
      - name: Verify AMP ⚡
        run: npm run test
