name: Test Jekyll Build
permissions:
  contents: read
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true
          cache-version: 0
      - name: Install node dependencies
        run: npm install
      - name: Build site
        run: |
          npm run build:css
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          NODE_ENV: production
      - name: Optimize AMP ⚡ and Minify HTML 🗜
        run: |
          sudo chmod -R 777 ./_site
          npx gulp build
      - name: Verify AMP ⚡
        run: npm run test
